name: Deploy

on:
  push:
    branches:
      - main

jobs:
  release-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/www.xyphuz.com:latest
          cache-from: >-
            type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/www.xyphuz.com:buildcache
          cache-to: >-
            type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/www.xyphuz.com:buildcache,mode=max

  deploy-to-vps:
    needs: release-docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Restart Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.HOST_PORT }}
          script: |
            docker stop www.xyphuz.com && docker rm www.xyphuz.com
            docker pull wst24365888/www.xyphuz.com:latest
            docker run --name www.xyphuz.com -p ${{ secrets.DOCKER_HOST_PORT }}:3000 -d wst24365888/www.xyphuz.com:latest
